# ============================================================
# SOUNDBOX TRAINING DATA
# ============================================================
#
# Soundbox LED/MQTT troubleshooting training data, originally from
# speech_assistant.py (SOUNDBOX_TRAINING_DATA). 105 instruction/
# response examples across 10 intents, embedded directly here so
# this module has no dependency on any other script. Used by
# match_training_response() to ground and speed up responses before
# falling back to the LLM.
#
# Carried over verbatim from the reference MQTT server.py.
SOUNDBOX_TRAINING_DATA = [
    {"instruction": "My transaction is not being voiced.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "Payment received but Soundbox didn't announce it.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "My customer paid but there was no voice announcement.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "Why is my transaction not speaking?", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "The payment was successful but Soundbox didn't announce it.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "My Soundbox stopped announcing transactions.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "customer payd but no sound came from the machine", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "why is my device not telling me about the payment", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "soundbox not speaking after payment", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "no announcement after successful payment, why?", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "the speaker didnt say anything after the payment went thru", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "My machine received the money but did not say anything out loud.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "Soundbox silent even though payment shows successful on my phone.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "why the box not talking after transaction", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "Payment done, but the device didn't say the amount.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "I got paid but the Soundbox never spoke the transaction.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "Transactions are not coming to my Soundbox.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "My Soundbox is not receiving payments.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "Payment notification is not coming.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "Customer paid but no payment announcement came.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "My device isn't getting any transaction alerts at all.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "None of my payments are reaching the Soundbox today.", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "the machine is not getting any transactions since morning", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. Since transaction notifications arrive through MQTT, the device needs an active network connection to receive them at all.", "intent": "transaction_not_received", "led_state": None},
    {"instruction": "My Soundbox has a blinking blue light and payment is not announced.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait for the device to connect. Since transaction notifications are received through MQTT, the transaction may not reach the Soundbox while it is not connected.", "intent": "transaction_troubleshooting", "led_state": "blinking_blue"},
    {"instruction": "Blue light keeps blinking and my customer's payment wasn't announced.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait for the device to connect. Since transaction notifications are received through MQTT, the transaction may not reach the Soundbox while it is not connected.", "intent": "transaction_troubleshooting", "led_state": "blinking_blue"},
    {"instruction": "blue led blinking, no voice for the payment i got", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait for the device to connect. Since transaction notifications are received through MQTT, the transaction may not reach the Soundbox while it is not connected.", "intent": "transaction_troubleshooting", "led_state": "blinking_blue"},
    {"instruction": "My Soundbox has a solid blue light but payment is not announced.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A solid blue LED indicates that the Soundbox is connected to the network and ready to use. Since the device appears to have network connectivity, further transaction or voice troubleshooting may be required.", "intent": "transaction_troubleshooting", "led_state": "solid_blue"},
    {"instruction": "Light is solid blue, everything looks connected, but no announcement for the payment.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A solid blue LED indicates that the Soundbox is connected to the network and ready to use. Since the device appears to have network connectivity, further transaction or voice troubleshooting may be required.", "intent": "transaction_troubleshooting", "led_state": "solid_blue"},
    {"instruction": "solid blue light but device still not saying the transaction amount", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A solid blue LED indicates that the Soundbox is connected to the network and ready to use. Since the device appears to have network connectivity, further transaction or voice troubleshooting may be required.", "intent": "transaction_troubleshooting", "led_state": "solid_blue"},
    {"instruction": "Red light blinking and payment didn't get announced.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking red LED means the Soundbox is not connected. Since transaction notifications are received through MQTT, the device won't receive or announce transactions while it is disconnected.", "intent": "transaction_troubleshooting", "led_state": "blinking_red"},
    {"instruction": "my light is red and blinking, no voice for the payment", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking red LED means the Soundbox is not connected. Since transaction notifications are received through MQTT, the device won't receive or announce transactions while it is disconnected.", "intent": "transaction_troubleshooting", "led_state": "blinking_red"},
    {"instruction": "Red blinking light, customer says they paid but nothing announced.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking red LED means the Soundbox is not connected. Since transaction notifications are received through MQTT, the device won't receive or announce transactions while it is disconnected.", "intent": "transaction_troubleshooting", "led_state": "blinking_red"},
    {"instruction": "Green light blinking and Soundbox not announcing anything.", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM is properly detected, as the Soundbox needs it to connect to the network and receive transaction notifications.", "intent": "transaction_troubleshooting", "led_state": "blinking_green"},
    {"instruction": "green led blinking, box not saying the payment out loud", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM is properly detected, as the Soundbox needs it to connect to the network and receive transaction notifications.", "intent": "transaction_troubleshooting", "led_state": "blinking_green"},
    {"instruction": "Solid green light, is that why my payment isn't announced?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected. The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "A solid green LED means the device is still turning on. Please wait for it to finish starting up — once it's ready, check whether the LED turns solid blue before expecting transaction announcements.", "intent": "transaction_troubleshooting", "led_state": "solid_green"},
    {"instruction": "My Soundbox is offline.", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "My Soundbox is not connecting to the network.", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "Why is the red light blinking?", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "device shows red blinking, whats wrong", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "my box seems disconnected, red light on", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "Soundbox not connected at all, red blinking non stop", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "network keeps dropping, red led blinking again and again", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the Soundbox is not connected. Please check the network in your area and confirm the device has signal, since it needs a connection to receive transactions through MQTT.", "intent": "network_not_connected", "led_state": "blinking_red"},
    {"instruction": "My Soundbox keeps searching for the network.", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait a moment for it to connect. Once connected, the LED should turn solid blue.", "intent": "network_searching", "led_state": "blinking_blue"},
    {"instruction": "Why is the blue light blinking?", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait a moment for it to connect. Once connected, the LED should turn solid blue.", "intent": "network_searching", "led_state": "blinking_blue"},
    {"instruction": "blue light keeps flashing, is it connecting?", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait a moment for it to connect. Once connected, the LED should turn solid blue.", "intent": "network_searching", "led_state": "blinking_blue"},
    {"instruction": "device stuck on blinking blue for a long time", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait a moment for it to connect. Once connected, the LED should turn solid blue.", "intent": "network_searching", "led_state": "blinking_blue"},
    {"instruction": "my machine won't stop searching for network, blue blinking", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait a moment for it to connect. Once connected, the LED should turn solid blue.", "intent": "network_searching", "led_state": "blinking_blue"},
    {"instruction": "why does the blue led keep blinking and not turn solid", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the Soundbox is searching for a network. Please wait a moment for it to connect. Once connected, the LED should turn solid blue.", "intent": "network_searching", "led_state": "blinking_blue"},
    {"instruction": "Is my Soundbox connected now? Light is solid blue.", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Yes, a solid blue LED means the Soundbox is connected to the network and ready to use.", "intent": "network_connected", "led_state": "solid_blue"},
    {"instruction": "solid blue light, does that mean its connected", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Yes, a solid blue LED means the Soundbox is connected to the network and ready to use.", "intent": "network_connected", "led_state": "solid_blue"},
    {"instruction": "Blue light stopped blinking and is now steady, is it ready?", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Yes, a solid blue LED means the Soundbox is connected to the network and ready to use.", "intent": "network_connected", "led_state": "solid_blue"},
    {"instruction": "My device shows a solid blue LED, all good?", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Yes, a solid blue LED means the Soundbox is connected to the network and ready to use.", "intent": "network_connected", "led_state": "solid_blue"},
    {"instruction": "light turned solid blue, is the box online now", "context": "The Soundbox needs an active network connection to receive transaction notifications via MQTT. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Yes, a solid blue LED means the Soundbox is connected to the network and ready to use.", "intent": "network_connected", "led_state": "solid_blue"},
    {"instruction": "What does solid green mean?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on.", "intent": "led_status_query", "led_state": "solid_green"},
    {"instruction": "Why is my green light not blinking, just steady?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on.", "intent": "led_status_query", "led_state": "solid_green"},
    {"instruction": "green light is on and not flashing, what does that mean", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on.", "intent": "led_status_query", "led_state": "solid_green"},
    {"instruction": "solid green led, what's that about", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on.", "intent": "led_status_query", "led_state": "solid_green"},
    {"instruction": "What does blinking green mean?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected.", "intent": "led_status_query", "led_state": "blinking_green"},
    {"instruction": "Is there a problem with my SIM?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected.", "intent": "led_status_query", "led_state": "blinking_green"},
    {"instruction": "why is the green light flashing", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected.", "intent": "led_status_query", "led_state": "blinking_green"},
    {"instruction": "green led keeps blinking, sim issue?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected.", "intent": "led_status_query", "led_state": "blinking_green"},
    {"instruction": "Why is the blue light blinking?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the device is searching for a network.", "intent": "led_status_query", "led_state": "blinking_blue"},
    {"instruction": "what does a flashing blue led mean", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the device is searching for a network.", "intent": "led_status_query", "led_state": "blinking_blue"},
    {"instruction": "blue light flashing on my soundbox, meaning?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the device is searching for a network.", "intent": "led_status_query", "led_state": "blinking_blue"},
    {"instruction": "why does my device show blinking blue", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking blue LED means the device is searching for a network.", "intent": "led_status_query", "led_state": "blinking_blue"},
    {"instruction": "What does solid blue mean?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid blue LED means the device is connected to the network and ready to use.", "intent": "led_status_query", "led_state": "solid_blue"},
    {"instruction": "blue light is steady, not flashing, what does that indicate", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid blue LED means the device is connected to the network and ready to use.", "intent": "led_status_query", "led_state": "solid_blue"},
    {"instruction": "what does it mean when the blue led stays on", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid blue LED means the device is connected to the network and ready to use.", "intent": "led_status_query", "led_state": "solid_blue"},
    {"instruction": "solid blue led meaning please", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid blue LED means the device is connected to the network and ready to use.", "intent": "led_status_query", "led_state": "solid_blue"},
    {"instruction": "Why is the red light blinking?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the device is not connected.", "intent": "led_status_query", "led_state": "blinking_red"},
    {"instruction": "what does a flashing red led mean on the soundbox", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the device is not connected.", "intent": "led_status_query", "led_state": "blinking_red"},
    {"instruction": "red light keeps blinking, what's wrong", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the device is not connected.", "intent": "led_status_query", "led_state": "blinking_red"},
    {"instruction": "meaning of blinking red light on my device", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking red LED means the device is not connected.", "intent": "led_status_query", "led_state": "blinking_red"},
    {"instruction": "Is there a problem with my SIM card?", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "green light blinking, sim card issue?", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "does blinking green mean my sim is not working", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "my sim card might not be detected, light is flashing green", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "sim not detected, whats the fix", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "why does it say sim card problem, green light flashing", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "green led blinking non stop, sim related?", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "is my sim inserted properly, green light keeps blinking", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "device can't find my sim card, green blinking led", "context": "The Soundbox requires a detected SIM card to connect to the mobile network. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A blinking green LED means the SIM card was not detected. Please check that the SIM card is properly detected by the device.", "intent": "sim_not_detected", "led_state": "blinking_green"},
    {"instruction": "Why is my green light solid, is it starting up?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on. This is normal right after power-up — wait for it to finish starting.", "intent": "device_starting", "led_state": "solid_green"},
    {"instruction": "green led steady on, is the device booting", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on. This is normal right after power-up — wait for it to finish starting.", "intent": "device_starting", "led_state": "solid_green"},
    {"instruction": "solid green light, is my soundbox turning on", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on. This is normal right after power-up — wait for it to finish starting.", "intent": "device_starting", "led_state": "solid_green"},
    {"instruction": "device just powered on, green light solid, normal?", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on. This is normal right after power-up — wait for it to finish starting.", "intent": "device_starting", "led_state": "solid_green"},
    {"instruction": "just plugged it in, green light is steady, is that ok", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on. This is normal right after power-up — wait for it to finish starting.", "intent": "device_starting", "led_state": "solid_green"},
    {"instruction": "green light on and steady after power on, what's happening", "context": "The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "A solid green LED means the device is turning on. This is normal right after power-up — wait for it to finish starting.", "intent": "device_starting", "led_state": "solid_green"},
    {"instruction": "My Soundbox is not working properly.", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "something seems wrong with my machine today", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "soundbox acting weird, what should i check first", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "device not behaving normally, any quick checks?", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "what should i check if my soundbox has issues", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "soundbox trouble, where do i start checking", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "my payment device isnt working right, first steps?", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "general problem with my soundbox, help", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "soundbox not working as expected, what to check", "context": "General Soundbox device status and troubleshooting. The Soundbox status LED: solid green = turning on, blinking green = SIM not detected, blinking blue = searching for network, solid blue = network connected and ready, blinking red = not connected.", "response": "Please start by checking the Soundbox's network connection and LED status. The LED color and pattern can tell you whether the device is starting up, searching for network, missing a SIM, connected and ready, or disconnected.", "intent": "general_soundbox_troubleshooting", "led_state": None},
    {"instruction": "My Soundbox is not receiving payments today, any idea why?", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "device didnt tell me about the last 2 payments", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "customer says paid, soundbox quiet", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "no voice output for recent transactions", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "transaction went through on my app but soundbox stayed silent", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "why does the speaker not say anything after a sale", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "sound box not confirming payments out loud anymore", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
    {"instruction": "payment confirmed on phone but soundbox made no sound", "context": "The Soundbox receives transaction notifications through MQTT and requires network connectivity to receive and announce transactions.", "response": "Please check the Soundbox's network connection and LED status. The Soundbox receives transaction notifications through MQTT, so if it isn't connected to the network, the transaction notification may not reach the device.", "intent": "transaction_not_announced", "led_state": None},
]

# ============================================================
# TRAINING-DATA INTENT MATCHING
# ============================================================
#
# Before calling the LLM, the transcript is checked against this data:
#   - A confident match returns the canonical response directly --
#     faster, cheaper, and guaranteed consistent for the same issue.
#   - A weaker match still contributes its "context" as grounding for
#     the LLM call, so the model stays on-script instead of inventing
#     an explanation.
#   - No match at all falls back to the LLM exactly as before.

import difflib
import os

TRAINING_MATCH_THRESHOLD = float(os.getenv("TRAINING_MATCH_THRESHOLD", "0.72"))

# One canonical (response, context) per intent, taken from the first
# training row seen for that intent.
TRAINING_BY_INTENT = {}
for _row in SOUNDBOX_TRAINING_DATA:
    TRAINING_BY_INTENT.setdefault(
        _row["intent"],
        {"response": _row["response"], "context": _row["context"]}
    )


def match_training_response(user_text):
    """
    Compare transcribed text against the known merchant phrasings in
    SOUNDBOX_TRAINING_DATA using fuzzy string matching.

    Returns:
        (response, intent, score)

        response is the canonical response text if the best match
        clears TRAINING_MATCH_THRESHOLD, otherwise None (caller should
        fall back to the LLM, optionally using `intent`'s context as a
        grounding hint).
    """

    if not user_text:
        return None, None, 0.0

    normalized = user_text.strip().lower()

    best_score = 0.0
    best_intent = None

    for row in SOUNDBOX_TRAINING_DATA:
        score = difflib.SequenceMatcher(
            None, normalized, row["instruction"].strip().lower()
        ).ratio()

        if score > best_score:
            best_score = score
            best_intent = row["intent"]

    if best_intent and best_score >= TRAINING_MATCH_THRESHOLD:
        return TRAINING_BY_INTENT[best_intent]["response"], best_intent, best_score

    return None, best_intent, best_score